# This file was automatically generated by pywxrc, do not edit by hand.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res


class xrcMAINFRAME(wx.Frame):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "MAINFRAME")
        self.PostCreate(pre)

        # Define variables for the controls
        self.MAINMENUBAR = self.GetMenuBar()
        self.MENU_GAME = xrc.XRCCTRL(self, "MENU_GAME")
        self.SINGLEGAME = xrc.XRCCTRL(self, "SINGLEGAME")
        self.MENUEASY = self.MAINMENUBAR.FindItemById(xrc.XRCID("MENUEASY"))
        self.MENUNORMAL = self.MAINMENUBAR.FindItemById(xrc.XRCID("MENUNORMAL"))
        self.MENUHARD = self.MAINMENUBAR.FindItemById(xrc.XRCID("MENUHARD"))
        self.MENURESUME = self.MAINMENUBAR.FindItemById(xrc.XRCID("MENURESUME"))
        self.TWOPLAYERGAME = xrc.XRCCTRL(self, "TWOPLAYERGAME")
        self.NETPLAYGAME = xrc.XRCCTRL(self, "NETPLAYGAME")
        self.MENUGIVEUP = self.MAINMENUBAR.FindItemById(xrc.XRCID("MENUGIVEUP"))
        self.MENUQUIT = self.MAINMENUBAR.FindItemById(xrc.XRCID("MENUQUIT"))
        self.MENU_FUNC = xrc.XRCCTRL(self, "MENU_FUNC")
        self.MENUHINT = self.MAINMENUBAR.FindItemById(xrc.XRCID("MENUHINT"))
        self.MENUSHUFFLE = self.MAINMENUBAR.FindItemById(xrc.XRCID("MENUSHUFFLE"))
        self.MENUPAUSEPROCEED = self.MAINMENUBAR.FindItemById(xrc.XRCID("MENUPAUSEPROCEED"))
        self.MENUHIDE = self.MAINMENUBAR.FindItemById(xrc.XRCID("MENUHIDE"))
        self.MENU_CONF = xrc.XRCCTRL(self, "MENU_CONF")
        self.MENU_MARK = xrc.XRCCTRL(self, "MENU_MARK")
        self.MENU_ABOUT = xrc.XRCCTRL(self, "MENU_ABOUT")
        self.MENUITEM_HOWTOPLAY = self.MAINMENUBAR.FindItemById(xrc.XRCID("MENUITEM_HOWTOPLAY"))
        self.MENUITEM_ABOUT = self.MAINMENUBAR.FindItemById(xrc.XRCID("MENUITEM_ABOUT"))
        self.LABEL_DIFF = xrc.XRCCTRL(self, "LABEL_DIFF")
        self.LABEL_LEVEL = xrc.XRCCTRL(self, "LABEL_LEVEL")
        self.LABEL_LIFE = xrc.XRCCTRL(self, "LABEL_LIFE")
        self.LABEL_HINT = xrc.XRCCTRL(self, "LABEL_HINT")
        self.LABEL_CHANGE = xrc.XRCCTRL(self, "LABEL_CHANGE")
        self.GAUGE_TIME = xrc.XRCCTRL(self, "GAUGE_TIME")
        self.LABEL_SCORE = xrc.XRCCTRL(self, "LABEL_SCORE")


class xrcABOUT(wx.Dialog):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "ABOUT")
        self.PostCreate(pre)

        # Define variables for the controls
        self.ABOUT_THANKS = xrc.XRCCTRL(self, "ABOUT_THANKS")
        self.ABOUT_CLOSE = xrc.XRCCTRL(self, "ABOUT_CLOSE")


class xrcHOWTOPLAY(wx.Dialog):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "HOWTOPLAY")
        self.PostCreate(pre)

        # Define variables for the controls


class xrcTHANKS(wx.Dialog):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "THANKS")
        self.PostCreate(pre)

        # Define variables for the controls



# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('pyllk.xrc')
